### ISSUE TITLE
Repeat progress updates

### ISSUE THREAD

**Issue by imcompiling** [drallgood/audiobookshelf-hardcover-sync#9]
I am getting my activity log flooded with repeat duplicate updates on a book read percentage. I am currently reading 2 books at once on ABS but it seems like only 1 is getting the duplicate updates. I listened to one before going to bed last night, and that is the book that is getting the hourly update without any new progress.

**Comment by imcompiling** [comment]
![Image](https://github.com/user-attachments/assets/4c395381-cfe2-4531-85be-8ab57284545e)

Seems like it is starting a new read every time it updates.

**Comment by imcompiling** [comment]
I am using v1.6.1. Here is my compose file:

```yaml
services:
  abs-hc-sync:
    image: ghcr.io/drallgood/audiobookshelf-hardcover-sync:v1.6.1
    container_name: "ABS_HC_Syncronizer"
    restart: unless-stopped
    environment:
      - AUDIOBOOKSHELF_TOKEN=${AUDIOBOOKSHELF_TOKEN}
      - AUDIOBOOKSHELF_URL=${AUDIOBOOKSHELF_URL}
      - HARDCOVER_SYNC_DELAY_MS=10000
      - HARDCOVER_TOKEN=${HARDCOVER_TOKEN}
      - MISMATCH_JSON_FILE=/home/data
      - SYNC_INTERVAL=1h
      - SYNC_STATE_FILE=/home/data/sync_state.json
      - SYNC_WANT_TO_READ=false
      - TZ=EST
    volumes:
      - db:/home/data

volumes:
  db: 
```
